# Generated by Django 5.0.2 on 2025-06-06 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_remove_blog_author_blog_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='section',
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blog.blog'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
