# Generated by Django 5.0.2 on 2025-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='work_domain',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
