# Generated by Django 5.0.2 on 2025-06-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_admin_work_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('admin', 'slug')},
        ),
    ]
