# Generated by Django 5.0.2 on 2025-09-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_documentcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcontent',
            name='chunks_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
