# Generated by Django 5.0.2 on 2025-10-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_documentcontent_chunks_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
