# Generated by Django 5.0.2 on 2025-10-18 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcontent',
            name='chunks_data',
        ),
        migrations.AlterField(
            model_name='documentcontent',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word Document'), ('IMG', 'Image')], max_length=4),
        ),
    ]
