# Generated by Django 5.0.2 on 2025-10-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_documentcontent_chunks_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcontent',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
