# Generated by Django 5.0.2 on 2025-10-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_documentcontent_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcontent',
            name='summaries',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
