# Generated by Django 5.0.2 on 2025-11-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_documentcontent_summaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='temp_media_file',
            field=models.FileField(blank=True, null=True, upload_to='blog_media/'),
        ),
        migrations.AlterField(
            model_name='documentcontent',
            name='type',
            field=models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word Document'), ('IMG', 'Image'), ('WEB', 'Webpage')], max_length=4),
        ),
    ]
