# Generated by Django 5.0.2 on 2025-11-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_temp_media_file_alter_documentcontent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='temp_media_file',
        ),
        migrations.AddField(
            model_name='admin',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
