# Generated by Django 5.0.2 on 2025-11-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_admin_image_remove_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
