# Generated by Django 5.0.2 on 2025-12-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.CharField(choices=[('slide', 'Slide'), ('webpage', 'Webpage')], default='slide', max_length=10),
        ),
    ]
