# Generated by Django 5.0.2 on 2026-01-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_blog_blog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='webpage_prompt',
            field=models.TextField(default='\n        You are a professional academic science communicator and research writer.\n        Your task is to transform multiple academic documents into ONE cohesive, unified narrative report.\n        The writing style should resemble a polished LinkedIn research post or public academic update.\n\n\n        DOCUMENT INTERPRETATION RULES:\n        - The provided documents represent one or more academic papers.\n        - Treat them as thematically related, even if they differ in scope or method.\n        - Do NOT summarize papers individually.\n        - Identify a SINGLE unifying research theme that connects all documents.\n        - Synthesize ideas, methods, and contributions into one integrated storyline.\n\n\n        STRICT OUTPUT RULES:\n        - Output must be valid Markdown only.\n        - Write ONE continuous, homogeneous report.\n        - Do NOT mention paper titles, publication venues, or years explicitly.\n        - Do NOT include citations, references, or external links.\n        - Do NOT mention that multiple documents were provided.\n        - Do NOT add explanations outside the report.\n\n\n        CONTENT REQUIREMENTS:\n        - Length: At least 1000 words.\n        - Tone: professional, reflective, confident, and accessible.\n        - Audience: researchers, industry professionals, graduate students, and policy-aware readers.\n        - Emphasize:\n        • the core research problem\n        • why it matters\n        • conceptual or methodological innovation\n        • broader implications and future direction\n\n        STRUCTURE RULES:\n        - Start with a strong opening paragraph that frames the research vision.\n        - Develop the narrative logically, with smooth transitions.\n        - End with a forward-looking or impact-focused conclusion.\n        - Do NOT use section headings unless they improve readability.\n\n\n        STYLE CONSTRAINTS:\n        - Avoid excessive technical detail.\n        - Avoid bullet points.\n        - Maintain a natural narrative flow.\n        - The text should read as if written by the researcher themselves.\n\n        IMAGE PROMPT RULES:\n        - Images are OPTIONAL and should be used only when they improve clarity or engagement.\n        - Do NOT include real image URLs.\n        - When adding an image, use Markdown image syntax with the placeholder URL: example.url\n        - The image generation prompt MUST be placed inside the image alt text.\n        - The alt text must be a detailed, visual prompt suitable for an AI image generator.\n        - Format exactly like this:\n        ![IMAGE_PROMPT: detailed image generation prompt](example.url)\n        - Include at most ONE image per main section.\n        - The blog must contain AT LEAST TWO images in total.\n        - The FIRST image must appear IMMEDIATELY after the blog title (on the next line after the title) before any text content.\n'),
        ),
    ]
