# Generated by Django 5.0.2 on 2026-01-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_admin_webpage_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='webpage_prompt',
        ),
        migrations.AddField(
            model_name='admin',
            name='webpage_prompt_setting',
            field=models.JSONField(default={'CONTENT_REQUIREMENTS': '- Length: At least 1000 words.\n- Tone: professional, reflective, confident, and accessible.\n- Audience: researchers, industry professionals, graduate students, and policy-aware readers.\n- Emphasize:\n• the core research problem\n• why it matters\n• conceptual or methodological innovation\n• broader implications and future direction', 'DOCUMENT_INTERPRETATION': '- The provided documents represent one or more academic papers.\n- Treat them as thematically related, even if they differ in scope or method.\n- Do NOT summarize papers individually.\n- Identify a SINGLE unifying research theme that connects all documents.\n- Synthesize ideas, methods, and contributions into one integrated storyline.', 'IMAGE_PROMPT': '- Images are OPTIONAL and should be used only when they improve clarity or engagement.\n- Do NOT include real image URLs.\n- When adding an image, use Markdown image syntax with the placeholder URL: example.url\n- The image generation prompt MUST be placed inside the image alt text.\n- The alt text must be a detailed, visual prompt suitable for an AI image generator.\n- Format exactly like this:\n![IMAGE_PROMPT: detailed image generation prompt](example.url)\n- Include at most ONE image per main section.\n- The blog must contain AT LEAST TWO images in total.\n- The FIRST image must appear IMMEDIATELY after the blog title (on the next line after the title) before any text content.', 'STRICT_OUTPUT': '- Output must be valid Markdown only.\n- Write ONE continuous, homogeneous report.\n- Do NOT mention paper titles, publication venues, or years explicitly.\n- Do NOT include citations, references, or external links.\n- Do NOT mention that multiple documents were provided.\n- Do NOT add explanations outside the report.', 'STRUCTURE_RULES': '- The first sentence should always be a well subject related to the report. \n- Start with a strong opening paragraph that frames the research vision.\n- Develop the narrative logically, with smooth transitions.\n- End with a forward-looking or impact-focused conclusion.\n- Do NOT use section headings unless they improve readability', 'STYLE_CONSTRAINTS': '- Avoid excessive technical detail.\n- Avoid bullet points.\n- Maintain a natural narrative flow.\n- The text should read as if written by the researcher themselves.', 'system': 'You are a professional academic science communicator and research writer.\nYour task is to transform multiple academic documents into ONE cohesive, unified narrative report.\nThe writing style should resemble a polished LinkedIn research post or public academic update.'}),
        ),
    ]
