# Generated by Django 5.0.2 on 2026-01-21 13:43

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_admin_webpage_prompt_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='readyblog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='webpage_prompt',
            field=models.JSONField(default=blog.models.default_webpage_prompt),
        ),
    ]
