# Generated by Django 5.0.2 on 2026-01-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blog_readyblog_alter_admin_webpage_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcontent',
            name='summaries',
        ),
        migrations.AddField(
            model_name='documentcontent',
            name='summarize_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
